// Automatically generated by astro-icon
// 5deac3355da34803de30a6289a27d3cdd2f505eb4bbcb29636cb43c5790dd5b0

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:github"
		| "fa:instagram"
		| "fa:linkedin"
		| "fa:youtube"
		| "fa:twitter"
		| "lucide:badge-check"
		| "lucide:chart-no-axes-column-increasing"
		| "lucide:briefcase-business"
		| "lucide:circle-check-big"
		| "lucide:clock-4"
		| "lucide:command"
		| "lucide:house"
		| "lucide:library"
		| "lucide:mail-plus"
		| "lucide:move-right"
		| "lucide:notebook-pen"
		| "lucide:notepad-text"
		| "lucide:palette"
		| "lucide:pen-line"
		| "lucide:rotate-ccw"
		| "lucide:rss"
		| "lucide:settings"
		| "lucide:square-user"
		| "lucide:monitor-cog"
		| "lucide:bar-chart"
		| "lucide:home"
		| "ri:quill-pen-fill"
		| "astro-icon"
		| "dot"
		| "linked";
}