// Automatically generated by astro-icon
// 4edc63e8273400fb75ec49b24ae970a5693ff99482322e5d708c2e4ea0a018fb
// 4edc63e8273400fb75ec49b24ae970a5693ff99482322e5d708c2e4ea0a018fb

declare module "virtual:astro-icon" {
  export type Icon =
    | "fa:github"
    | "fa:instagram"
    | "fa:linkedin"
    | "fa:youtube"
    | "fa:twitter"
    | "lucide:badge-check"
    | "lucide:chart-no-axes-column-increasing"
    | "lucide:briefcase-business"
    | "lucide:circle-check-big"
    | "lucide:clock-4"
    | "lucide:command"
    | "lucide:house"
    | "lucide:library"
    | "lucide:mail-plus"
    | "lucide:moon-star"
    | "lucide:move-right"
    | "lucide:notebook-pen"
    | "lucide:notepad-text"
    | "lucide:pen-line"
    | "lucide:rotate-ccw"
    | "lucide:rss"
    | "lucide:settings"
    | "lucide:square-user"
    | "lucide:sun"
    | "lucide:zap"
    | "lucide:bar-chart"
    | "lucide:home"
    | "ri:quill-pen-fill"
    | "astro-icon"
    | "linked";
}
