// Automatically generated by astro-icon
// de475b5def21cd9f1cce4254bf91bcc273e03fd9c72a964840029dd78fa519b3

declare module "virtual:astro-icon" {
  export type Icon =
    | "fa:github"
    | "fa:instagram"
    | "fa:linkedin"
    | "fa:youtube"
    | "fa:twitter"
    | "lucide:badge-check"
    | "lucide:chart-no-axes-column-increasing"
    | "lucide:briefcase-business"
    | "lucide:circle-check-big"
    | "lucide:clock-4"
    | "lucide:command"
    | "lucide:house"
    | "lucide:library"
    | "lucide:mail-plus"
    | "lucide:palette"
    | "lucide:palette"
    | "lucide:move-right"
    | "lucide:notebook-pen"
    | "lucide:notepad-text"
    | "lucide:pen-line"
    | "lucide:rotate-ccw"
    | "lucide:rss"
    | "lucide:settings"
    | "lucide:square-user"
    | "lucide:sun"
    | "lucide:monitor-cog"
    | "lucide:bar-chart"
    | "lucide:home"
    | "ri:quill-pen-fill"
    | "astro-icon"
    | "dot"
    | "linked";
}
