blank_issues_enabled: false
contact_links:
  - name: 🖥️ Website Bugs or Feature Requests
    url: https://github.com/princemuel/princemuel.com
    about: "This repository is for the content and the website"
  - name: 💡 Ideas, Content Requests and Questions
    url: https://github.com/princemuel/princemuel.com/discussions
    about: "Have an idea? Want to see content on a particular topic? Open a discussion here"
  - name: 💬 Join the Discord Community
    url: https://discord.gg/fbFCkYabZB
    about: "Outside of GitHub, the Odin community lives on Discord. Join our server here"
