name: 📝 Suggest an Improvement to Post Content
description: Point out a broken link or a typo, suggest another resource or make a suggestion
title: "<Post>: <Short description of your suggestion>"
labels: ["Status: Needs Triage"]
assignees:
  - nil
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a suggestion! Please fill out these fields so your issue can be reviewed - giving the right amount of detail makes it much easier for maintainers to process.

        If you have any questions or are unsure about anything, don't be afraid to ask! The maintainers are here to help.
  - type: checkboxes
    slug: contributing
    attributes:
      label: Checks
      description: Please fill out the following checkboxes
      options:
        - label: This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/princemuel/princemuel.com/issues) to make sure)
          required: true
        - label: I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/princemuel/princemuel.com/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: Would you like to work on this issue?
          required: false
  - type: textarea
    slug: suggested-changes
    attributes:
      label: Describe your suggestion
      description: A description of your suggestion. You can provide screenshots or additional context if relevant
      placeholder: ex 'There is a typo in the additional resource section - it should be wombat, not combat'
    validations:
      required: true
  - type: dropdown
    slug: path
    attributes:
      label: Path
      description: Which path does your suggestion affect?
      multiple: true
      options:
        - Foundations
        - Ruby / Rails
        - Node / JS
        - Other / NA
    validations:
      required: true
  - type: input
    slug: resource-url
    attributes:
      label: Resource Url
      description: A link to the relevant resource, or the content that needs to be fixed. If not applicable, describe where to look for your suggestion
      placeholder: ex. https://www.princemuel.com/blog/just-another-blog-post
    validations:
      required: true

  - type: input
    slug: contact
    attributes:
      label: (Optional) Discord Name
      description: Optionally provide your discord name to help coordinate changes there if necessary
      placeholder: ex. odinite
    validations:
      required: false
  - type: textarea
    slug: additional-comments
    attributes:
      label: (Optional) Additional Comments
      description: "Anything else you'd like to cover"
      placeholder: We ❤️ open source
    validations:
      required: false
