name: Deploy Database Changes

on:
  push:
    paths:
      - prisma/migrations/** # Only run this workflow when migrations are updated
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      # - name: install pnpm
      #   run: |
      #     curl -fsSL https://get.pnpm.io/install.sh | sh -

      - name: install dependencies
        run: npm install

      - name: apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
